sudo: required

language: generic

services:
    - docker

before_install:
    - docker build -t karinatitov/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true karinatitov/docker-react npm run test



